spring:
  profiles.active: dev
---
spring:
  profiles: dev
  jpa:
    properties:       hibernate: 
       dialect: org.hibernate.dialect.Oracle10gDialect
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: dvdrental
    password: dvdrental
    driver-class-name: oracle.jdbc.OracleDriver
logging:
  file: logs/dev_app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework: info
    guru.springframework.controllers: info
    org.hibernate: info

management:
  endpoints:
   enabled-by-default: true
   web.exposure: 
    include: "*" 
   jmx:
      exposure:
        include: "*"
  endpoint:
    info:
      enabled: true
    beans:                                                               
      enabled: true  
    prometheus:                                                               
      enabled: true    
    metrics:     enabled: true
          
   
---
spring:
  profiles: production
logging:
  file: logs/production_app.log
  pattern:
    file: "%d %-5level [%thread] %logger{0} : %msg%n"
  level:
    org.springframework.web: WARN
    guru.springframework.controllers: WARN
    org.hibernate: WARN